name: Fetch Playbooks from Private Repo

on:
  workflow_dispatch:

jobs:
  fetch_and_run_playbooks:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Public Repository
        uses: actions/checkout@v4 # Check out the public repo

      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: arthur-plazanet/config
          ref: feature/add-ansible-basic-config
          token: ${{ secrets.CONFIG_PRIVATE_REPO_TOKEN }}

      - name: Create .ssh Directory
        run: mkdir -p ~/.ssh # Ensure the .ssh directory exists

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts  # Add host key to known_hosts

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }} # Your SSH key for connecting to servers

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip docker-ce
          sudo pip3 install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventories/hosts ansible/main.yml
