name: Audit Lighthouse
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Name of the application'
        required: true
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: ${{ github.event.inputs.app_name }}
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
