# https://www.sitespeed.io/documentation/sitespeed.io/continuous-integration/#github-actions
name: sitespeed.io
on:
  push:
    branches:
      - main

jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:30.3.0 https://www.sitespeed.io 
        # --budget.configPath .github/budget.json -n 1
